# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c7e8fc41025e19898235712a58f6ea6e165d803e84ebe251b3c534c6f3ebf0525aecaf343b17c327b34116acbb173a58830407068da5abc793f92df06dadfe

test:
  secret_key_base: 15ca85c6734d2717538c8fefe206591119729e7dd53d5f2164c2639eb1dd2b009e0b1e1d12c95adfbc9356626ddd46a6f25d0a4e055f58b479871c09ac636155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
